replicaCount: 2

image:
  repository: 302174038725.dkr.ecr.ap-northeast-2.amazonaws.com/ticketing/reserv-svc
  tag: a1b2c3d
  pullPolicy: Always

service:
  port: 5000

# 나중에 수정하기 (f->t)
autoscaling:
  enabled: false   
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: ticketing-sa
