apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_WRITER_HOST: "{{ .Values.env.DB_WRITER_HOST }}"
  DB_USER: "{{ .Values.env.DB_USER }}"

  REDIS_HOST: "{{ .Values.env.REDIS_HOST }}"
  SQS_QUEUE_URL: "{{ .Values.env.SQS_QUEUE_URL }}"