apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Release.Name }}

    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: {{ .Release.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # liveness (프로세스 살아있는지만 체크)
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep python | grep -v grep"
            initialDelaySeconds: 20
            periodSeconds: 15

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"