apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: ticketing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::302174038725:role/ticketing-ssm-role